package com.hf.spring.mybatis.entity;

import com.hf.spring.mybatis.entity.base.DataEntity;
import java.util.Date;

public class Role extends DataEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_type
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sort
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_type
     *
     * @return the value of role.role_type
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_type
     *
     * @param roleType the value for role.role_type
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_user
     *
     * @return the value of role.create_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_user
     *
     * @param createUser the value for role.create_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_date
     *
     * @return the value of role.create_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_date
     *
     * @param createDate the value for role.create_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_user
     *
     * @return the value of role.update_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_user
     *
     * @param updateUser the value for role.update_user
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_date
     *
     * @return the value of role.update_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_date
     *
     * @param updateDate the value for role.update_date
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.sort
     *
     * @return the value of role.sort
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.sort
     *
     * @param sort the value for role.sort
     *
     * @mbg.generated Sun Feb 12 08:29:44 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}